networks:
  rocket_network:
    driver: bridge
services:
  mysql:
    container_name: rocket-db 
    image: mysql:latest
    restart: always
    ports:
      - 3366:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: go_test
      MYSQL_USER: kanjiro
      MYSQL_PASSWORD: 12345678
    networks:
      - rocket_network

  golang:
    container_name: rocket-backend
    build:
      context: ./server/.
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    links:
      - mysql
    depends_on:
      - mysql
    env_file:
      - ./server/.env
    networks:
      - rocket_network
  nextjs:
      container_name: rocket-app
      build:
        context: ./admin/.
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      volumes:
        - ./app:/usr/app
      networks:
        - rocket_network
