import "../../styles/globals.css";
import type { Metadata } from "next";
import TeamSwitcher from "@/components/team-switcher";
import { Search } from "@/components/search";
import { UserNav } from "@/components/user-nav";
import { cookies } from "next/headers";
import { Toaster } from "@/components/ui/toaster";
import { getLoggedInUser } from "@/api-requests/auth";
import { redirect } from "next/navigation";
import { ThemeProviders } from "@/components/themeProvider";
import { Ubuntu } from "next/font/google";
import StoreInit from "@/store/StoreInit";
const josefin = Ubuntu({
 subsets: ["latin"],
 weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
 title: "Backbone Dashboard",
 description: "Generated by backbone team",
};

export default async function RootLayout({
 children,
}: {
 children: React.ReactNode;
}) {
 const nextCookies = cookies();
 const token = nextCookies.get("jwt");
 const config = {
  headers: { Cookie: `${token?.name}=${token?.value}` },
  withCredentials: true,
 };
 const response = await getLoggedInUser(config);
 if (!response.ok) {
  redirect("/login");
 }

 return (
  <html lang="en" className="bg-[#F6F7FA]">
   <body className={`${josefin.className}  bg-[#F6F7FA]`}>
    <ThemeProviders>
    <StoreInit user={response.user} />
     <div className="hidden flex-col md:flex ">
      <div className="border-b bg-black">
       <div className="flex h-16 items-center px-4">
        <TeamSwitcher shops={response.user.shops} />
        <div className="ml-auto flex items-center space-x-4">
         <Search />
         <UserNav />
        </div>
       </div>
      </div>
     </div>
     <div className="">
      <div className="flex " id="main">
       <div className="w-full overflow-y-auto max-h-screen pb-20 flex-1 px-10 mt-2">{children}</div>
      </div>
      <Toaster />
     </div>
    </ThemeProviders>
   </body>
  </html>
 );
}
